version : '2'

services:
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      #- ./backup14abril:/dump

volumes:
  mongodb:
  mongodb_config:
